### ISSUE TITLE
can't login to image from links in repo

### ISSUE THREAD

**Issue by mdxtinkernick** [turtlebot/turtlebot4_setup#1]
I have burnt the image [turtlebot4_lite_galactic_0.1.1.zip](http://download.ros.org/downloads/turtlebot4/turtlebot4_lite_galactic_0.1.1.zip) onto an sd card and booted a raspberry pi with it plugged in.

I cannot get passed the login - ubuntu/ubuntu is not working, nor ubuntu/Turtlebot4

Has it had a different password set on it ? Cannot find anything in the documentation except ubuntu/ubuntu in the instructions for building your own from scratch, and the ubuntu/Turtlebot4 combination in the clear path bringup video for a TurtleBot

**Comment by roni-kreinin** [comment]
The password should be `turtlebot4` with all lowercase.
