### ISSUE TITLE
unable to SSH after running turtlebot_setup.sh script

### ISSUE THREAD

**Issue by ipa-rar** [turtlebot/turtlebot4_setup#5]
**Please provide the following information:**
 - OS: (e.g. Ubuntu 22.04)
 - ROS Distro: (e.g. Humble)
 - installed:

 **Expected behaviour**
ssh back into the turtlebot4 after installing and rebooting

 **Actual behaviour**
 - static IP changes 
 - unable to establish ssh connection with the new IP address
 - Robot does not respond after rebooting

**To Reproduce**
Provide the steps to reproduce:
1. run `wget -qO - https://raw.githubusercontent.com/turtlebot/turtlebot4_setup/humble/scripts/turtlebot4_setup.sh | bash`
2. in this line ``https://github.com/turtlebot/turtlebot4_setup/blob/038d6f881ed56748d5727bc43c449084a628e591/scripts/turtlebot4_setup.sh#L48`` the netplan yaml is removed and this might cause the issue

**Comment by VishnuVelayuthan** [comment]
Hey, suffering from the same bug^^^^ I can't ssh as well. 

I'm also having an issue where the different ros packages are also not being able to be located by apt. I am unable to run turtlebot4-setup as my computer is saying it is not a command

**Comment by ipa-rar** [comment]
@VishnuVelayuthan @roni-kreinin 
I have found a workaround for this problem. I stopped following the documentation found in the readme and this helped me a lot.  Especially this ``wget -qO - https://raw.githubusercontent.com/turtlebot/turtlebot4_setup/humble/scripts/turtlebot4_setup.sh | bash`` command caused the ssh to break as it simply removed the netplan yaml file ``sudo rm /etc/netplan/50-cloud-init.yaml``. 

``https://github.com/turtlebot/turtlebot4_setup/tree/humble-readme`` This provides more steps on configuring but this is also not fail proof. I will write a documentation if I succeed in setting this up and would send a PR.  

And `turtlebot4-setup` is not a command and its an alias which in turn should run `ros2 run turtlebot4_setup turtlebot4_setup`. You can check the aliases [here](https://github.com/turtlebot/turtlebot4_setup/blob/humble/etc/turtlebot4/aliases.bash). 

**Honestly, turtlebot is something one can use out of box but this version is very buggy and not a direct out of the box usable robot for a multi robot use case.** 


_PS: I own four Turtlebot4 robots_

**Comment by roni-kreinin** [comment]
@ipa-rar The `turtlebot4_setup.sh` script is used to set up the actual humble image from a clean ubuntu 22.04 server image. Unless you want to make a modified version of the turtlebot4 image, I would recommend just downloading the built image from http://download.ros.org/downloads/turtlebot4/ and flashing that.

**Comment by ipa-rar** [comment]
I have flashed the prebuilt image using the documentation provided in the Readme but when the robot boots up it boots into BusyBox as shown here. 
![tb4_01](https://user-images.githubusercontent.com/49311464/232746169-24b1a6c5-5a82-4f6e-ac56-79f80d2ecf03.png)

Then flashing the card using[ Balena Etcher](https://www.balena.io/etcher) helped to boot up the robot with the new image. 

I am closing this issue as the issue was more or less solved.
